//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class actividad
    {
        public int act_id { get; set; }
        public string act_enf_estado { get; set; }
        public string act_enf_descripcion { get; set; }
        public string act_enf_fecha { get; set; }
        public string act_enf_empresa { get; set; }
        public string act_acc_estado { get; set; }
        public string act_acc_descripcion { get; set; }
        public string act_acc_capacidad { get; set; }
        public string act_acc_fecha { get; set; }
        public string act_acc_empresa { get; set; }
    
        public virtual paciente paciente { get; set; }
    }
}
