//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cie10
    {
        public cie10()
        {
            this.sub_cie10 = new HashSet<sub_cie10>();
        }
    
        public int cie_id { get; set; }
        public string cie_codigo { get; set; }
        public string cie_descripcion { get; set; }
    
        public virtual ICollection<sub_cie10> sub_cie10 { get; set; }
    }
}
