//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class codigo
    {
        public int cod_id { get; set; }
        public string cod_codigo { get; set; }
        public byte[] cod_imagen { get; set; }
        public int cod_registro { get; set; }
        public int cod_area { get; set; }
    
        public virtual area area { get; set; }
        public virtual registro registro { get; set; }
    }
}
