//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor
    {
        public int doc_id { get; set; }
        public string doc_cedula { get; set; }
        public string doc_nombres { get; set; }
        public string doc_codigo { get; set; }
        public int doc_especialidad { get; set; }
        public string doc_correo { get; set; }
        public byte[] doc_firma { get; set; }
        public bool doc_estado { get; set; }
        public int doc_empresa { get; set; }
    
        public virtual empresa empresa { get; set; }
    }
}
