//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class especialidad
    {
        public especialidad()
        {
            this.medico = new HashSet<medico>();
            this.doctor = new HashSet<doctor>();
        }
    
        public int esp_id { get; set; }
        public string esp_nombre { get; set; }
    
        public virtual ICollection<medico> medico { get; set; }
        public virtual ICollection<doctor> doctor { get; set; }
    }
}
