//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class examen
    {
        public examen()
        {
            this.control = new HashSet<control>();
            this.valores = new HashSet<valores>();
            this.prueba = new HashSet<prueba>();
        }
    
        public int exa_id { get; set; }
        public string exa_nombre { get; set; }
        public string exa_unidad { get; set; }
        public string exa_tipo { get; set; }
        public int exa_area { get; set; }
        public Nullable<int> exa_item { get; set; }
        public string exa_valores { get; set; }
        public string exa_inicial { get; set; }
        public string exa_estado { get; set; }
    
        public virtual area area { get; set; }
        public virtual ICollection<control> control { get; set; }
        public virtual ICollection<valores> valores { get; set; }
        public virtual ICollection<prueba> prueba { get; set; }
    }
}
