//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class familiar
    {
        public int fam_id { get; set; }
        public bool fam_cardiopatia { get; set; }
        public string fam_car_txt { get; set; }
        public bool fam_diabetes { get; set; }
        public string fam_dia_txt { get; set; }
        public bool fam_cardiovascular { get; set; }
        public string fam_vas_txt { get; set; }
        public bool fam_hipertension { get; set; }
        public string fam_hip_txt { get; set; }
        public bool fam_cancer { get; set; }
        public string fam_can_txt { get; set; }
        public bool fam_tuberculosis { get; set; }
        public string fam_tub_txt { get; set; }
        public bool fam_mental { get; set; }
        public string fam_men_txt { get; set; }
        public bool fam_infecciosa { get; set; }
        public string fam_inf_txt { get; set; }
        public bool fam_malformacion { get; set; }
        public string fam_mal_txt { get; set; }
        public bool fam_otro { get; set; }
        public string fam_otr_txt { get; set; }
        public bool fam_hipotiroidismo { get; set; }
        public string fam_hit_txt { get; set; }
    
        public virtual paciente paciente { get; set; }
    }
}
