//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fisico
    {
        public int fis_id { get; set; }
        public bool fis_piel { get; set; }
        public string fis_pie_txt { get; set; }
        public bool fis_cabeza { get; set; }
        public string fis_cab_txt { get; set; }
        public bool fis_ojos { get; set; }
        public string fis_ojo_txt { get; set; }
        public bool fis_oidos { get; set; }
        public string fis_oid_txt { get; set; }
        public bool fis_nariz { get; set; }
        public string fis_nar_txt { get; set; }
        public bool fis_boca { get; set; }
        public string fis_boc_txt { get; set; }
        public bool fis_faringe { get; set; }
        public string fis_far_txt { get; set; }
        public bool fis_cuello { get; set; }
        public string fis_cue_txt { get; set; }
        public bool fis_axilas { get; set; }
        public string fis_axi_txt { get; set; }
        public bool fis_torax { get; set; }
        public string fis_tor_txt { get; set; }
        public bool fis_abdomen { get; set; }
        public string fis_abd_txt { get; set; }
        public bool fis_columna { get; set; }
        public string fis_col_txt { get; set; }
        public bool fis_ingle { get; set; }
        public string fis_ing_txt { get; set; }
        public bool fis_mie_sup { get; set; }
        public string fis_msp_txt { get; set; }
        public bool fis_mie_inf { get; set; }
        public string fis_mif_txt { get; set; }
        public bool fis_organos { get; set; }
        public string fis_org_txt { get; set; }
        public bool fis_respiratorio { get; set; }
        public string fis_res_txt { get; set; }
        public bool fis_cardiovascular { get; set; }
        public string fis_car_txt { get; set; }
        public bool fis_digestivo { get; set; }
        public string fis_dig_txt { get; set; }
        public bool fis_genital { get; set; }
        public string fis_fen_txt { get; set; }
        public bool fis_urinario { get; set; }
        public string fis_uri_txt { get; set; }
        public bool fis_esqueletico { get; set; }
        public string fis_esq_txt { get; set; }
        public bool fis_endocrino { get; set; }
        public string fis_end_txt { get; set; }
        public bool fis_linfatico { get; set; }
        public string fis_lin_txt { get; set; }
        public bool fis_neurologico { get; set; }
        public string fis_neu_txt { get; set; }
    
        public virtual historia historia { get; set; }
    }
}
