//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class habitos
    {
        public int hab_id { get; set; }
        public string hab_fumo { get; set; }
        public string hab_fuma { get; set; }
        public Nullable<int> hab_cigarillos { get; set; }
        public string hab_alcohol { get; set; }
        public string hab_frecuencia { get; set; }
        public string hab_drogas { get; set; }
        public string hab_ejercicio { get; set; }
    
        public virtual paciente paciente { get; set; }
    }
}
