//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inmunizacion
    {
        public int inm_id { get; set; }
        public int inm_vacuna { get; set; }
        public string inm_fecha { get; set; }
        public string inm_tipo { get; set; }
        public int inm_paciente { get; set; }
    
        public virtual paciente paciente { get; set; }
        public virtual vacuna vacuna { get; set; }
    }
}
