//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_kinnemed02Entities : DbContext
    {
        public bd_kinnemed02Entities()
            : base("name=bd_kinnemed02Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<canton> canton { get; set; }
        public DbSet<componente> componente { get; set; }
        public DbSet<empresa> empresa { get; set; }
        public DbSet<especialidad> especialidad { get; set; }
        public DbSet<pais> pais { get; set; }
        public DbSet<profesion> profesion { get; set; }
        public DbSet<provincia> provincia { get; set; }
        public DbSet<valores> valores { get; set; }
        public DbSet<area> area { get; set; }
        public DbSet<control> control { get; set; }
        public DbSet<perfil> perfil { get; set; }
        public DbSet<prueba> prueba { get; set; }
        public DbSet<fisico> fisico { get; set; }
        public DbSet<revision> revision { get; set; }
        public DbSet<cie10> cie10 { get; set; }
        public DbSet<diagnostico> diagnostico { get; set; }
        public DbSet<sub_cie10> sub_cie10 { get; set; }
        public DbSet<plan> plan { get; set; }
        public DbSet<familiar> familiar { get; set; }
        public DbSet<personal> personal { get; set; }
        public DbSet<signos> signos { get; set; }
        public DbSet<subsecuente> subsecuente { get; set; }
        public DbSet<audiometria> audiometria { get; set; }
        public DbSet<espirometria> espirometria { get; set; }
        public DbSet<rayos> rayos { get; set; }
        public DbSet<inmunizacion> inmunizacion { get; set; }
        public DbSet<riesgo> riesgo { get; set; }
        public DbSet<vacuna> vacuna { get; set; }
        public DbSet<ocupacional> ocupacional { get; set; }
        public DbSet<laboral> laboral { get; set; }
        public DbSet<examen> examen { get; set; }
        public DbSet<historia> historia { get; set; }
        public DbSet<registro> registro { get; set; }
        public DbSet<oftalmologia> oftalmologia { get; set; }
        public DbSet<concepto> concepto { get; set; }
        public DbSet<ginecologico> ginecologico { get; set; }
        public DbSet<trabajador> trabajador { get; set; }
        public DbSet<laboratorista> laboratorista { get; set; }
        public DbSet<medico> medico { get; set; }
        public DbSet<paciente> paciente { get; set; }
    }
}
