//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class bd_kinnemed02Entities : DbContext
    {
        public bd_kinnemed02Entities()
            : base("name=bd_kinnemed02Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<canton> canton { get; set; }
        public DbSet<empresa> empresa { get; set; }
        public DbSet<especialidad> especialidad { get; set; }
        public DbSet<pais> pais { get; set; }
        public DbSet<profesion> profesion { get; set; }
        public DbSet<provincia> provincia { get; set; }
        public DbSet<valores> valores { get; set; }
        public DbSet<area> area { get; set; }
        public DbSet<control> control { get; set; }
        public DbSet<perfil> perfil { get; set; }
        public DbSet<fisico> fisico { get; set; }
        public DbSet<revision> revision { get; set; }
        public DbSet<cie10> cie10 { get; set; }
        public DbSet<diagnostico> diagnostico { get; set; }
        public DbSet<sub_cie10> sub_cie10 { get; set; }
        public DbSet<plan> plan { get; set; }
        public DbSet<familiar> familiar { get; set; }
        public DbSet<signos> signos { get; set; }
        public DbSet<subsecuente> subsecuente { get; set; }
        public DbSet<inmunizacion> inmunizacion { get; set; }
        public DbSet<riesgo> riesgo { get; set; }
        public DbSet<vacuna> vacuna { get; set; }
        public DbSet<ocupacional> ocupacional { get; set; }
        public DbSet<laboral> laboral { get; set; }
        public DbSet<ginecologico> ginecologico { get; set; }
        public DbSet<trabajador> trabajador { get; set; }
        public DbSet<laboratorista> laboratorista { get; set; }
        public DbSet<codigo> codigo { get; set; }
        public DbSet<prueba> prueba { get; set; }
        public DbSet<historia> historia { get; set; }
        public DbSet<reposo> reposo { get; set; }
        public DbSet<paciente> paciente { get; set; }
        public DbSet<medico> medico { get; set; }
        public DbSet<registro> registro { get; set; }
        public DbSet<audiometria> audiometria { get; set; }
        public DbSet<espirometria> espirometria { get; set; }
        public DbSet<oftalmologia> oftalmologia { get; set; }
        public DbSet<rayos> rayos { get; set; }
        public DbSet<examen> examen { get; set; }
        public DbSet<orden> orden { get; set; }
        public DbSet<concepto> concepto { get; set; }
        public DbSet<personal> personal { get; set; }
        public DbSet<accidente> accidente { get; set; }
        public DbSet<actividad> actividad { get; set; }
        public DbSet<enfermedad> enfermedad { get; set; }
        public DbSet<habitos> habitos { get; set; }
        public DbSet<doctor> doctor { get; set; }
    
        public virtual ObjectResult<getReporte01_Result> getReporte01(string fecha_ini, string fecha_fin)
        {
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("fecha_ini", fecha_ini) :
                new ObjectParameter("fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getReporte01_Result>("getReporte01", fecha_iniParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<getReporte02_Result> getReporte02(string fecha_ini, string fecha_fin)
        {
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("fecha_ini", fecha_ini) :
                new ObjectParameter("fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getReporte02_Result>("getReporte02", fecha_iniParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<getReporte03_Result> getReporte03(string fecha_ini, string fecha_fin)
        {
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("fecha_ini", fecha_ini) :
                new ObjectParameter("fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getReporte03_Result>("getReporte03", fecha_iniParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<getReporte04_Result> getReporte04(string fecha_ini, string fecha_fin)
        {
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("fecha_ini", fecha_ini) :
                new ObjectParameter("fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getReporte04_Result>("getReporte04", fecha_iniParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<getReporte05_Result> getReporte05(string fecha_ini, string fecha_fin)
        {
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("fecha_ini", fecha_ini) :
                new ObjectParameter("fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getReporte05_Result>("getReporte05", fecha_iniParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<getReporte06_Result> getReporte06(string fecha_ini, string fecha_fin)
        {
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("fecha_ini", fecha_ini) :
                new ObjectParameter("fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getReporte06_Result>("getReporte06", fecha_iniParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<getReporte07_Result> getReporte07(string fecha_ini, string fecha_fin)
        {
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("fecha_ini", fecha_ini) :
                new ObjectParameter("fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getReporte07_Result>("getReporte07", fecha_iniParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<getReporte08_Result> getReporte08(string fecha_ini, string fecha_fin)
        {
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("fecha_ini", fecha_ini) :
                new ObjectParameter("fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getReporte08_Result>("getReporte08", fecha_iniParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<getReporte09_Result> getReporte09(string fecha_ini, string fecha_fin)
        {
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("fecha_ini", fecha_ini) :
                new ObjectParameter("fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getReporte09_Result>("getReporte09", fecha_iniParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<getReporte10_Result> getReporte10(string fecha_ini, string fecha_fin)
        {
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("fecha_ini", fecha_ini) :
                new ObjectParameter("fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getReporte10_Result>("getReporte10", fecha_iniParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<getReporte11_Result> getReporte11(string fecha_ini, string fecha_fin)
        {
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("fecha_ini", fecha_ini) :
                new ObjectParameter("fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getReporte11_Result>("getReporte11", fecha_iniParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<getReporte12_Result> getReporte12(string fecha_ini, string fecha_fin)
        {
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("fecha_ini", fecha_ini) :
                new ObjectParameter("fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getReporte12_Result>("getReporte12", fecha_iniParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<Lista01> getLista01(string fecha_ini, string fecha_fin)
        {
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("fecha_ini", fecha_ini) :
                new ObjectParameter("fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Lista01>("getLista01", fecha_iniParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<Lista02> getLista02(string fecha_ini, string fecha_fin)
        {
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("fecha_ini", fecha_ini) :
                new ObjectParameter("fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Lista02>("getLista02", fecha_iniParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<Lista03> getLista03(string fecha_ini, string fecha_fin)
        {
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("fecha_ini", fecha_ini) :
                new ObjectParameter("fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Lista03>("getLista03", fecha_iniParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<Lista04> getLista04(string fecha_ini, string fecha_fin)
        {
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("fecha_ini", fecha_ini) :
                new ObjectParameter("fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Lista04>("getLista04", fecha_iniParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<Lista05> getLista05(string fecha_ini, string fecha_fin)
        {
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("fecha_ini", fecha_ini) :
                new ObjectParameter("fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Lista05>("getLista05", fecha_iniParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<Lista06> getLista06(string fecha_ini, string fecha_fin)
        {
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("fecha_ini", fecha_ini) :
                new ObjectParameter("fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Lista06>("getLista06", fecha_iniParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<Lista07> getLista07(string fecha_ini, string fecha_fin)
        {
            var fecha_iniParameter = fecha_ini != null ?
                new ObjectParameter("fecha_ini", fecha_ini) :
                new ObjectParameter("fecha_ini", typeof(string));
    
            var fecha_finParameter = fecha_fin != null ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Lista07>("getLista07", fecha_iniParameter, fecha_finParameter);
        }
    }
}
