//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class laboratorista
    {
        public laboratorista()
        {
            this.registro = new HashSet<registro>();
            this.rayos = new HashSet<rayos>();
            this.audiometria = new HashSet<audiometria>();
            this.espirometria = new HashSet<espirometria>();
        }
    
        public int lab_id { get; set; }
    
        public virtual ICollection<registro> registro { get; set; }
        public virtual ICollection<rayos> rayos { get; set; }
        public virtual ICollection<audiometria> audiometria { get; set; }
        public virtual ICollection<espirometria> espirometria { get; set; }
    }
}
