//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class laboral
    {
        public int lab_id { get; set; }
        public int lab_ocupacional { get; set; }
        public int lab_riesgo { get; set; }
        public bool lab_estado { get; set; }
    
        public virtual ocupacional ocupacional { get; set; }
        public virtual riesgo riesgo { get; set; }
    }
}
