//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medico
    {
        public medico()
        {
            this.registro = new HashSet<registro>();
        }
    
        public int med_id { get; set; }
        public string med_cedula { get; set; }
        public string med_nombres { get; set; }
        public string med_apellidos { get; set; }
        public string med_ci { get; set; }
        public string med_codigo { get; set; }
        public int med_especialidad { get; set; }
        public string med_correo { get; set; }
        public string med_estado { get; set; }
    
        public virtual especialidad especialidad { get; set; }
        public virtual ICollection<registro> registro { get; set; }
    }
}
