//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medico
    {
        public medico()
        {
            this.registro = new HashSet<registro>();
            this.historia = new HashSet<historia>();
            this.audiometria = new HashSet<audiometria>();
            this.espirometria = new HashSet<espirometria>();
            this.oftalmologia = new HashSet<oftalmologia>();
            this.rayos = new HashSet<rayos>();
        }
    
        public int med_id { get; set; }
    
        public virtual especialidad especialidad { get; set; }
        public virtual ICollection<registro> registro { get; set; }
        public virtual ICollection<historia> historia { get; set; }
        public virtual ICollection<audiometria> audiometria { get; set; }
        public virtual ICollection<espirometria> espirometria { get; set; }
        public virtual ICollection<oftalmologia> oftalmologia { get; set; }
        public virtual ICollection<rayos> rayos { get; set; }
    }
}
