//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ocupacional
    {
        public ocupacional()
        {
            this.laboral = new HashSet<laboral>();
        }
    
        public int ocu_id { get; set; }
        public string ocu_empresa { get; set; }
        public string ocu_seccion { get; set; }
        public string ocu_cargo { get; set; }
        public string ocu_descripcion { get; set; }
        public string ocu_jornada { get; set; }
        public string ocu_inicio { get; set; }
        public string ocu_fin { get; set; }
        public decimal ocu_tiempo { get; set; }
        public string ocu_maquinaria { get; set; }
        public string ocu_materiales { get; set; }
        public string ocu_sustancias { get; set; }
        public string ocu_equipo { get; set; }
        public string ocu_tipo { get; set; }
        public bool ocu_estado { get; set; }
        public int ocu_paciente { get; set; }
    
        public virtual ICollection<laboral> laboral { get; set; }
        public virtual paciente paciente { get; set; }
    }
}
