//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ocupacional
    {
        public ocupacional()
        {
            this.laboral = new HashSet<laboral>();
        }
    
        public int ocu_id { get; set; }
    
        public virtual ICollection<laboral> laboral { get; set; }
        public virtual paciente paciente { get; set; }
    }
}
