//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden
    {
        public int ord_id { get; set; }
        public int ord_paciente { get; set; }
        public int ord_examen { get; set; }
        public string ord_fecha { get; set; }
    
        public virtual paciente paciente { get; set; }
        public virtual examen examen { get; set; }
    }
}
