//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paciente
    {
        public paciente()
        {
            this.audiometria = new HashSet<audiometria>();
            this.espirometria = new HashSet<espirometria>();
            this.historia = new HashSet<historia>();
            this.inmunizacion = new HashSet<inmunizacion>();
            this.ocupacional = new HashSet<ocupacional>();
            this.oftalmologia = new HashSet<oftalmologia>();
            this.orden = new HashSet<orden>();
            this.rayos = new HashSet<rayos>();
            this.registro = new HashSet<registro>();
        }
    
        public int pac_id { get; set; }
    
        public virtual ICollection<audiometria> audiometria { get; set; }
        public virtual canton canton { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual ICollection<espirometria> espirometria { get; set; }
        public virtual familiar familiar { get; set; }
        public virtual ginecologico ginecologico { get; set; }
        public virtual ICollection<historia> historia { get; set; }
        public virtual ICollection<inmunizacion> inmunizacion { get; set; }
        public virtual ICollection<ocupacional> ocupacional { get; set; }
        public virtual ICollection<oftalmologia> oftalmologia { get; set; }
        public virtual ICollection<orden> orden { get; set; }
        public virtual pais pais { get; set; }
        public virtual profesion profesion { get; set; }
        public virtual personal personal { get; set; }
        public virtual ICollection<rayos> rayos { get; set; }
        public virtual ICollection<registro> registro { get; set; }
    }
}
