//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pais
    {
        public pais()
        {
            this.paciente = new HashSet<paciente>();
        }
    
        public int pais_id { get; set; }
        public string pais_nombre { get; set; }
    
        public virtual ICollection<paciente> paciente { get; set; }
    }
}
