//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfil
    {
        public perfil()
        {
            this.control = new HashSet<control>();
        }
    
        public int per_id { get; set; }
        public string per_nombre { get; set; }
        public string per_descripcion { get; set; }
    
        public virtual ICollection<control> control { get; set; }
    }
}
