//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class provincia
    {
        public provincia()
        {
            this.canton = new HashSet<canton>();
            this.paciente = new HashSet<paciente>();
        }
    
        public int pro_id { get; set; }
        public string pro_nombre { get; set; }
    
        public virtual ICollection<canton> canton { get; set; }
        public virtual ICollection<paciente> paciente { get; set; }
    }
}
