//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro
    {
        public registro()
        {
            this.prueba = new HashSet<prueba>();
        }
    
        public int reg_id { get; set; }
        public int reg_paciente { get; set; }
        public int reg_orden { get; set; }
        public string reg_fecha { get; set; }
        public Nullable<int> reg_medico { get; set; }
        public Nullable<bool> reg_estado { get; set; }
    
        public virtual medico medico { get; set; }
        public virtual ICollection<prueba> prueba { get; set; }
        public virtual paciente paciente { get; set; }
    }
}
