//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class revision
    {
        public int rev_id { get; set; }
        public bool rev_organos { get; set; }
        public string rev_org_txt { get; set; }
        public bool rev_respiratorio { get; set; }
        public string rev_res_txt { get; set; }
        public bool rev_cardiovascular { get; set; }
        public string rev_car_txt { get; set; }
        public bool rev_digestivo { get; set; }
        public string rev_dig_txt { get; set; }
        public bool rev_genital { get; set; }
        public string rev_gen_txt { get; set; }
        public bool rev_urinario { get; set; }
        public string rev_uri_txt { get; set; }
        public bool rev_musculo { get; set; }
        public string rev_mus_txt { get; set; }
        public bool rev_endocrino { get; set; }
        public string rev_end_txt { get; set; }
        public bool rev_linfatico { get; set; }
        public string rev_lin_txt { get; set; }
        public bool rev_nervioso { get; set; }
        public string rev_ner_txt { get; set; }
    
        public virtual historia historia { get; set; }
    }
}
