//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sub_cie10
    {
        public sub_cie10()
        {
            this.diagnostico = new HashSet<diagnostico>();
        }
    
        public int sub_id { get; set; }
        public string sub_codigo { get; set; }
        public string sub_descripcion { get; set; }
        public int sub_cie101 { get; set; }
    
        public virtual cie10 cie10 { get; set; }
        public virtual ICollection<diagnostico> diagnostico { get; set; }
    }
}
