//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subsecuente
    {
        public int sub_id { get; set; }
        public int sub_historia { get; set; }
        public string sub_fecha { get; set; }
        public string sub_hora { get; set; }
        public string sub_subjetivo { get; set; }
        public string sub_objetivo { get; set; }
        public string sub_analisis { get; set; }
        public string sub_plan { get; set; }
    
        public virtual historia historia { get; set; }
    }
}
