//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trabajador
    {
        public int tra_id { get; set; }
        public string tra_cedula { get; set; }
        public string tra_nombres { get; set; }
        public string tra_apellidos { get; set; }
        public string tra_correo { get; set; }
        public Nullable<bool> tra_estado { get; set; }
    }
}
