//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinnemed05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacuna
    {
        public vacuna()
        {
            this.inmunizacion = new HashSet<inmunizacion>();
        }
    
        public int vac_id { get; set; }
        public string vac_nombre { get; set; }
        public int vac_dosis { get; set; }
        public string vac_esquema { get; set; }
    
        public virtual ICollection<inmunizacion> inmunizacion { get; set; }
    }
}
